### ISSUE TITLE
Error creating stack

### ISSUE THREAD

**Issue by andrewoh531** [buildkite/elastic-ci-stack-for-aws#282]
I get the following error when creating the stack: `You must give the log-delivery group WRITE and READ_ACP permissions to the target bucket`. This errors when creating the `ManagedSecretsBucket` S3 bucket.

I'm using version 2.1.0 template and using default values (or no values) for almost all the parameters.

**Comment by lox** [comment]
Hi @andrewoh531, sorry about this! The auto-created secrets bucket is a new addition and it looks like there are some issues with it. 

I'd suggest creating an s3 bucket and passing it in as the `ManagedSecretsBucket` parameter and I'll investigate what is going on.

**Comment by andrewoh531** [comment]
No problems. I'm not in a rush so I'll wait for the fix to come out. Thanks!

**Comment by lox** [comment]
This is fixed in master @andrewoh531, you can update now via https://s3.amazonaws.com/buildkite-aws-stack/master/aws-stack.json or wait for the next stable release! Thanks again for the report!

**Comment by saarons** [comment]
I think there's still a problem with the secrets bucket creation. I'm running the master template and a secrets bucket is being created for me (which I want) but not being passed into the user data.

I think that the issue is that this variable name is ambiguous:
```
BUILDKITE_SECRETS_BUCKET=\"${SecretsBucket}\"
```

The parameter and the output are named the same thing and I think the `Fn::Sub` is picking up the parameter and not the output.

**Comment by lox** [comment]
Urgh, yup you are right @saarons. Will figure something out.
